version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka_kraft
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - ./config/server.properties:/opt/kafka/config/server.properties
      - ./data:/tmp/kraft-combined-logs_555
    environment:
      # Required to initialize storage for KRaft
      KAFKA_CLUSTER_ID: "OyYwOqNMS5OeYv7xH1m5vw=="
    command: >
      bash -c "
      if [ ! -f /tmp/kraft-combined-logs_555/meta.properties ]; then
        echo 'Formatting KRaft storage...'
        /opt/kafka/bin/kafka-storage.sh format \
          --config /opt/kafka/config/server.properties \
          --cluster-id OyYwOqNMS5OeYv7xH1m5vw== \
          --ignore-formatted
      fi;
      /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
      "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
